[build]
  command = "npm run build"
  publish = "frontend/dist"

[scripts]
  install-all = "npm install && cd frontend && npm install && cd ../backend && npm install"
  start = "node backend/server.js"

[functions]
  [functions.backend]
    handler = "backend/server.js"